name: Build Iconoclasm .deb
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & Build Tweak
        uses: Randomblock1/theos-action@v1
        with:
          theos-src: 'https://github.com/theos/theos'

      - name: Upload Finished .DEB File
        uses: actions/artifacts@v4
        with:
          name: Iconoclasm-Deb-Package
          path: packages/*.deb
